#! /bin/bash

#   Add service file to runlevel directory

/bin/cp /etc/init.d/{ntpsec-openrc,ntpsec-wait} /etc/runlevels/default || true


#   Add service to runlevel

rc-update add ntpsec default
rc-update add ntpsec-wait default


#   Update services list

rc-update -u
