#!/usr/bin/env bash

# Create directory for ntpsec
mkdir -p /var/log/ntpsec

# Check if the user ntpsec exists
if id "ntpsec" &>/dev/null; then
    chown ntpsec:ntpsec /var/log/ntpsec
else
    echo "Error: User ntpsec does not exist. Directory ownership not changed."
fi
